### ISSUE TITLE
What port is this running on?

### ISSUE THREAD

**Issue by jackson-sandland** [fubarnetes/webterm#207]
I run: `cargo run`.

Then my actual terminal shows the server is running: 
```
   Compiling webterm v0.2.0 (/Users/jacksonsandland/Development/webterm)
   Finished dev [unoptimized + debuginfo] target(s) in 2.89s
   Running `target/debug/webterm-server`
```
But I'm not sure where.
What port is the server running on?

**Comment by jackson-sandland** [comment]
I found it. The screenshot shows it at: `8080`

**Comment by fabianfreyer** [comment]
Awesome, and thanks for the PR!
